spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookcomm_db
    username: yasuke
    password: pedrotomaz09172314
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
  cache:
    type: redis

